# Generated by Django 5.2.13 on 2026-09-10 03:45

from django.db import migrations, models


# These values were derived from filter_type strings instead of handler names.
# Canonical values already in use must remain unchanged.
EVENT_ALIASES = {
    'StudentSettingsRenderStarted': 'AccountSettingsRenderStarted',
    'XblockRenderStarted': 'RenderXBlockStarted',
    'CourseHomepageUrlCreationStarted': 'CourseHomeUrlCreationStarted',
    'HomeEnrollmentApiRendered': 'CourseEnrollmentAPIRenderStarted',
    'HomeCourserunApiRenderedStarted': 'CourseRunAPIRenderStarted',
    'OraSubmissionViewRenderStarted': 'ORASubmissionViewRenderStarted',
    'IdvPageUrlRequested': 'IDVPageURLRequested',
    'CourseAboutPageUrlRequested': 'CourseAboutPageURLRequested',
    'ScheduleQuerysetRequested': 'ScheduleQuerySetRequested',
    'AuthoringLmsPageUrlRequested': 'LMSPageURLRequested',
}


def correct_event_names(apps, schema_editor):
    """Retain existing endpoint configuration while making its event dispatchable."""
    webfilters = apps.get_model('openedx_webhooks', 'Webfilter')
    for old_name, new_name in EVENT_ALIASES.items():
        webfilters.objects.using(schema_editor.connection.alias).filter(event=old_name).update(event=new_name)


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_webhooks', '0007_alter_webfilter_event'),
    ]

    operations = [
        migrations.RunPython(correct_event_names, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='webfilter',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='webfilter',
            name='event',
            field=models.CharField(choices=[('StudentLoginRequested', 'Student Login Requested'), ('StudentRegistrationRequested', 'Student Registration Requested'), ('AccountSettingsRenderStarted', 'Account Settings Render Started'), ('CourseEnrollmentStarted', 'Course Enrollment Started'), ('CourseUnenrollmentStarted', 'Course Unenrollment Started'), ('CertificateCreationRequested', 'Certificate Creation Requested'), ('CertificateRenderStarted', 'Certificate Render Started'), ('CohortChangeRequested', 'Cohort Change Requested'), ('CohortAssignmentRequested', 'Cohort Assignment Requested'), ('CourseAboutRenderStarted', 'Course About Render Started'), ('DashboardRenderStarted', 'Dashboard Render Started'), ('VerticalBlockChildRenderStarted', 'Vertical Block Child Render Started'), ('CourseEnrollmentQuerysetRequested', 'Course Enrollment Queryset Requested'), ('RenderXBlockStarted', 'Render X Block Started'), ('VerticalBlockRenderCompleted', 'Vertical Block Render Completed'), ('CourseHomeUrlCreationStarted', 'Course Home Url Creation Started'), ('CourseEnrollmentAPIRenderStarted', 'Course Enrollment API Render Started'), ('CourseRunAPIRenderStarted', 'Course Run API Render Started'), ('InstructorDashboardRenderStarted', 'Instructor Dashboard Render Started'), ('ORASubmissionViewRenderStarted', 'ORA Submission View Render Started'), ('IDVPageURLRequested', 'IDV Page URL Requested'), ('CourseAboutPageURLRequested', 'Course About Page URL Requested'), ('ScheduleQuerySetRequested', 'Schedule Query Set Requested'), ('LMSPageURLRequested', 'LMS Page URL Requested'), ('InstructorDashboardTabsRequested', 'Instructor Dashboard Tabs Requested'), ('AccountSettingsReadOnlyFieldsRequested', 'Account Settings Read Only Fields Requested'), ('GradeEventContextRequested', 'Grade Event Context Requested')], default='', help_text='Event type', max_length=50),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[('ROLE_ASSIGNMENT_CREATED', 'Role assignment created'), ('ROLE_ASSIGNMENT_DELETED', 'Role assignment deleted'), ('COURSE_CATALOG_INFO_CHANGED', 'Course catalog info changed'), ('XBLOCK_CREATED', 'Xblock created'), ('XBLOCK_UPDATED', 'Xblock updated'), ('XBLOCK_PUBLISHED', 'Xblock published'), ('XBLOCK_DELETED', 'Xblock deleted'), ('XBLOCK_DUPLICATED', 'Xblock duplicated'), ('COURSE_CERTIFICATE_CONFIG_CHANGED', 'Course certificate config changed'), ('COURSE_CERTIFICATE_CONFIG_DELETED', 'Course certificate config deleted'), ('COURSE_CREATED', 'Course created'), ('CONTENT_LIBRARY_CREATED', 'Content library created'), ('CONTENT_LIBRARY_UPDATED', 'Content library updated'), ('CONTENT_LIBRARY_DELETED', 'Content library deleted'), ('LIBRARY_BLOCK_CREATED', 'Library block created'), ('LIBRARY_BLOCK_UPDATED', 'Library block updated'), ('LIBRARY_BLOCK_DELETED', 'Library block deleted'), ('LIBRARY_BLOCK_PUBLISHED', 'Library block published'), ('CONTENT_OBJECT_TAGS_CHANGED', 'Content object tags changed'), ('CONTENT_OBJECT_ASSOCIATIONS_CHANGED', 'Content object associations changed'), ('LIBRARY_COLLECTION_CREATED', 'Library collection created'), ('LIBRARY_COLLECTION_UPDATED', 'Library collection updated'), ('LIBRARY_COLLECTION_DELETED', 'Library collection deleted'), ('LIBRARY_CONTAINER_CREATED', 'Library container created'), ('LIBRARY_CONTAINER_UPDATED', 'Library container updated'), ('LIBRARY_CONTAINER_DELETED', 'Library container deleted'), ('LIBRARY_CONTAINER_PUBLISHED', 'Library container published'), ('COURSE_IMPORT_COMPLETED', 'Course import completed'), ('COURSE_RERUN_COMPLETED', 'Course rerun completed'), ('STUDENT_REGISTRATION_COMPLETED', 'Student registration completed'), ('SESSION_LOGIN_COMPLETED', 'Session login completed'), ('COURSE_ENROLLMENT_CREATED', 'Course enrollment created'), ('COURSE_ENROLLMENT_CHANGED', 'Course enrollment changed'), ('COURSE_UNENROLLMENT_COMPLETED', 'Course unenrollment completed'), ('CERTIFICATE_CREATED', 'Certificate created'), ('CERTIFICATE_CHANGED', 'Certificate changed'), ('CERTIFICATE_REVOKED', 'Certificate revoked'), ('COHORT_MEMBERSHIP_CHANGED', 'Cohort membership changed'), ('COURSE_DISCUSSIONS_CHANGED', 'Course discussions changed'), ('PROGRAM_CERTIFICATE_REVOKED', 'Program certificate revoked'), ('PROGRAM_CERTIFICATE_AWARDED', 'Program certificate awarded'), ('PERSISTENT_GRADE_SUMMARY_CHANGED', 'Persistent grade summary changed'), ('XBLOCK_SKILL_VERIFIED', 'Xblock skill verified'), ('USER_NOTIFICATION_REQUESTED', 'User notification requested'), ('EXAM_ATTEMPT_SUBMITTED', 'Exam attempt submitted'), ('EXAM_ATTEMPT_REJECTED', 'Exam attempt rejected'), ('EXAM_ATTEMPT_VERIFIED', 'Exam attempt verified'), ('EXAM_ATTEMPT_ERRORED', 'Exam attempt errored'), ('EXAM_ATTEMPT_RESET', 'Exam attempt reset'), ('COURSE_ACCESS_ROLE_ADDED', 'Course access role added'), ('COURSE_ACCESS_ROLE_REMOVED', 'Course access role removed'), ('FORUM_THREAD_CREATED', 'Forum thread created'), ('FORUM_THREAD_RESPONSE_CREATED', 'Forum thread response created'), ('FORUM_RESPONSE_COMMENT_CREATED', 'Forum response comment created'), ('COURSE_NOTIFICATION_REQUESTED', 'Course notification requested'), ('ORA_SUBMISSION_CREATED', 'Ora submission created'), ('COURSE_PASSING_STATUS_UPDATED', 'Course passing status updated'), ('CCX_COURSE_PASSING_STATUS_UPDATED', 'Ccx course passing status updated'), ('BADGE_AWARDED', 'Badge awarded'), ('BADGE_REVOKED', 'Badge revoked'), ('IDV_ATTEMPT_CREATED', 'Idv attempt created'), ('IDV_ATTEMPT_PENDING', 'Idv attempt pending'), ('IDV_ATTEMPT_APPROVED', 'Idv attempt approved'), ('IDV_ATTEMPT_DENIED', 'Idv attempt denied'), ('EXTERNAL_GRADER_SCORE_SUBMITTED', 'External grader score submitted'), ('LTI_PROVIDER_LAUNCH_SUCCESS', 'Lti provider launch success')], default='', help_text='Event type', max_length=50),
        ),
    ]
